- hosts: localhost
  connection: local
  tasks:
    - name: launching ec2
      ec2:
       instance_type: t2.micro
       key_name: EssentialsKP
       image: ami-02f706d959cedf892
       region: us-east-2
       group: default
       count: 1
       vpc_subnet_id: subnet-92f6fafa
       wait: yes
       assign_public_ip: yes
